image: node:8.15.1

pipelines:
  default:
    - step:
        name: Deploy to heroku sleepy earth
        script:
          - meteor build ./build
          - pipe: atlassian/heroku-deploy:1.0.4
            variables:
              HEROKU_API_KEY: '***REMOVED***'
              HEROKU_APP_NAME: 'sleepy-earth-65615'
              ZIP_FILE: './build/V8-Alba.tar.gz'
              WAIT: 'true'
              DEBUG: 'true'
